<?php
/**
 * Fired when the plugin is uninstalled.
 *
 * @package Genpost_Thumbnails
 */

// If uninstall not called from WordPress, then exit.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

/**
 * Clean up plugin options and data for a single site.
 *
 * @return void
 */
function genpost_thumb_uninstall_cleanup() {
	// List of options to delete.
	$options_to_delete = array(
		'genpost_thumb_settings',
		'genpost_thumb_optin_dismissed',
	);

	foreach ( $options_to_delete as $option_name ) {
		delete_option( $option_name );
		delete_site_option( $option_name );
	}

	// Delete transients.
	delete_transient( 'genpost_thumb_api_status' );
	delete_site_transient( 'genpost_thumb_api_status' );

	// Delete all post meta created by the plugin using WordPress core APIs.
	delete_post_meta_by_key( '_genpost_thumb_autogenerated' );
	delete_post_meta_by_key( '_genpost_thumb_prompt' );
}

/**
 * Execute uninstallation cleanup across single site or multisite network.
 *
 * @return void
 */
function genpost_thumb_uninstall() {
	if ( is_multisite() ) {
		$genpost_thumb_site_ids = get_sites( array( 'fields' => 'ids' ) );
		$genpost_thumb_original = get_current_blog_id();

		foreach ( $genpost_thumb_site_ids as $genpost_thumb_site_id ) {
			switch_to_blog( (int) $genpost_thumb_site_id );
			genpost_thumb_uninstall_cleanup();
		}

		switch_to_blog( $genpost_thumb_original );
	} else {
		genpost_thumb_uninstall_cleanup();
	}
}

genpost_thumb_uninstall();
